# -*- coding: utf-8 -*-
"""downstream tasks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1awrH_qjoGWUE0TVCjhpbpwNCj87wkyAJ

## Setup
"""

import os
import shutil
import logging

from models import load_feat_model
from training import class_transfer_learn
from utils import setup

def run(args):
    strategy = setup(args)

    feat_model = load_feat_model(args, strategy)

    for ds_id in args.ds_ids:
        class_transfer_learn(args, strategy, feat_model, ds_id, args.downstream_path)

    logging.info('clearing local log folder')
    shutil.rmtree('./logs', ignore_errors=True)

    logging.info('downloading GCP logs')
    os.system(f'gsutil -m cp -r {args.downstream_path} ./logs')
    logging.info('GCP logs downloaded')

    tensorboard_cmd = "tensorboard dev upload " \
                      "--logdir logs " \
                      f"--name '{args.loss}, {args.data_id}, {args.backbone}' " \
                      "--one_shot"
    return tensorboard_cmd